project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - file: index.qmd
            icon: house
            text: About
          - icon: book
            text: Catalog
            href: https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/schmidtDSE/biodiversity-catalog/main/stac/v1/catalog.json?.language=en
          - examples.qmd

