project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - file: index.qmd
        icon: house
        text: About
      - icon: book
        text: Catalog
        href: https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/schmidtDSE/biodiversity-catalog/main/stac/v1/catalog.json?.language=en
      - icon: github
        text: GitHub repo
        href: https://github.com/schmidtDSE/biodiversity-catalog
      - icon: globe-americas
        text: DSE Home
        href: https://dse.berkeley.edu
      - section: Examples
        contents:
          - text: Cloud Basics
            href: examples/cloud-basics.qmd
          - text: STAC Search
            href: examples/stac_search.qmd
          - text: STAC Tiling
            href: examples/stac_tiling.qmd
          - text: Optimizing formats
            href: examples/ace.qmd
