---
title: "access"
format: html
---

This Biodiversity Dataset Catalog seeks to make a range of biodiversty data more readily discoverable and reusable.  Data listed here is designed to support access with portable, cloud native, high-performance protocols that avoid the need to download entire data files.

Data sources indexed here that are not already available on an external cloud-native storage platform will require access keys (see _Categories of Data Access_ below).  This is necessary to meet the licensing and distribution requirements of the data providers.


```{r}
```


```{python}
```

## Categories of Data Access

Datasets included in this catalog fall into several different categories of access:

1. Data that is publicly available from a high-bandwidth source in optimized format. 

2. Data that is freely available under permissive licenses, but only from low-bandwidth hosts or in non-optimized formats. Data shared on scientific data repositories such as Zenodo usually fall in this category.

3. Data that is freely available but under restricted use, typically requiring a request (automated or manual).  Such distributors often also have low-bandwidth distribution and formats of category 2.

4. Data that is shared only privately or under explicit non-disclosure contracts.

5. Sensitive or [sovereign data](https://www.gida-global.org/care) which can only be stored in approved geographic regions or accessed only from secure systems.


This catalog seeks to help research teams bridge across these diverse types and needs in biodiversity data while respecting necessary restrictions of each category using distributed and open source tooling. 
