# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push]

name: docker

jobs:
  docker:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    container: rocker/ml-verse
    steps:
      - uses: actions/checkout@v3
      
      - name: install
        run: |
          pip install stac-check

      - name: validate
        run: |
          stac-check stac/v1/catalog.json --recursive

